### ISSUE TITLE
tried running basic example

### ISSUE THREAD

**Issue by xmen4u** [ZEROFAIL/goblin-legacy#10]
Used conda to create the environment (python3.5)
ran pip install git+https://github.com/ZEROFAIL/goblin.git@dev#egg=goblin

tried running the basic example code (all imports work)

ERROR:tornado.application:Exception in callback <function execute_query.<locals>.on_connect at 0x104f01158> for <tornado.concurrent.Future object at 0x104a814e0>
Traceback (most recent call last):

ile "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 317, in _set_done
    cb(self)
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/goblin/connection.py", line 80, in on_connect
    request_id=request_id)
TypeError: send() got an unexpected keyword argument 'request_id'

Later on i've did some reading, edited titan-1.0.0-hadoop1/conf/gremlin-server/gremlin-server.yaml
changed channelizer to :
channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer

restarted titan server and response:
Traceback (most recent call last):
  File "basic.py", line 30, in <module>
    followers = loop.run_sync(go)
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "basic.py", line 18, in go
    goblin = yield User.create(name="Goblin")
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/goblin/models/vertex.py", line 368, in on_save
    stream = f.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/goblin/gremlin/base.py", line 291, in on_call
    stream = f.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/goblin/connection.py", line 73, in on_connect
    conn = f.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/gremlinclient/pool.py", line 124, in cb
    conn = f.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/gremlinclient/tornado_client/client.py", line 116, in get_conn
    conn = f.result()
  File "/Users/blurb/miniconda3/envs/titan/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 400: Bad Request

**Comment by davebshow** [comment]
Try installing gremlinclient from the github master branch:

```
pip install git+https://github.com/davebshow/gremlinclient.git
```

That should be a quick fix. Tomorrow I'll be updating the release etc.

**Comment by davebshow** [comment]
Goblin requires the WebSocketChannelizer

**Comment by xmen4u** [comment]
@davebshow Thanks so much for the quick reply! that worked!

Will it also support the 'HttpChannelizer' as well in the future?

**Comment by davebshow** [comment]
no problem @xmen4u. Very soon we will have an official 0.0.2 release available on pypi. We've been working on improving the docs as well: http://goblin.readthedocs.org/en/latest/?badge=latest
