### ISSUE TITLE
all() method is raising a gremin error

### ISSUE THREAD

**Issue by dusktreader** [ZEROFAIL/goblin-legacy#12]
I just started trying out goblin as my python binding to titan and with it the tinkerpop3 stack.  I tried out a few simple operations and was able to get it working fairly easily. I was just about to start writing (re-writing from py2neo in fact) my models to use goblin, but ran into this error. It seems to be coming from gremlin, and I slimmed down my code to the essentials to test it out.

Here is the code:

``` python
 from goblin import properties                                                                       
 from goblin import connection                                                                       
 from goblin.models import Vertex                                                                    

 from tornado import gen                                                                             
 from tornado.ioloop import IOLoop                                                                   


 class TestVertex(Vertex):                                                                           
     prop1 = properties.String()                                                                     


 @gen.coroutine                                                                                      
 def go():                                                                                           
     yield TestVertex.create(prop1='A')                                                              
     yield TestVertex.create(prop1='B')                                                              
     stream = yield TestVertex.all()                                                                 
     vertices = yield stream.read()                                                                  
     for vertex in vertices:                                                                         
         print(vertex)                                                                               


 if __name__ == '__main__':                                                                          
     connection.setup('ws://localhost:8182')                                                         
     loop = IOLoop.current()                                                                         
     try:                                                                                            
         print("start")                                                                              
         loop.run_sync(go)                                                                           
         print("end")                                                                                
     except Exception as err:                                                                        
         print("Caught an errror: {}".format(err))                                                   
         raise err                                                                                   
     finally:                                                                                        
         connection.tear_down()                                                                      
         loop.close()   
```

And here is the error:

```
$ python test.py
start
Caught an errror: 597 No such property: V for class: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    raise err
  File "test.py", line 28, in <module>
    loop.run_sync(go)
  File "/home/tbeck/.virtualenvs/goblin/lib/python3.5/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/home/tbeck/.virtualenvs/goblin/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/tbeck/.virtualenvs/goblin/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "test.py", line 18, in go
    vertices = yield stream.read()
  File "/home/tbeck/.virtualenvs/goblin/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/tbeck/.virtualenvs/goblin/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
RuntimeError: 597 No such property: V for class: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource
```

I need some of these basic ORM type methods to be working well before I can use goblin. Is this a problem with my implementation or with goblin's interface to gremlin?

**Comment by davebshow** [comment]
Thanks for reporting. There was a simple typo in the script causing this error. As it turns out, `all()` without the `ids` kwarg was not covered in the tests. Please try to install from the dev branch. This should fix the problem:

```
$ pip install git+https://github.com/ZEROFAIL/goblin.git@dev#egg=goblin
```

**Comment by dusktreader** [comment]
Hehe... you are fast! I just found the same thing and patched it in a fork. Guess that pull-request won't be necessary!

Thanks for the fast response.
